---
  - name: configure firewall to allow http/s and ssh from local network
    ufw: rule=allow src=10.0.0.0/23 port={{ item }} proto=tcp
    with_items:
    - 80
    - 443
    - 22

  - name: configure firewall to deny everything else
    ufw: state=enabled policy=reject

  - name: install nginx
    apt: pkg=nginx

  - name: write nginx.conf
    action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: ensure nginx is running and enabled
    service: name=nginx state=running enabled=yes
